# Generated by Django 3.2.8 on 2021-10-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20211022_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolistitem',
            options={'ordering': ('id',)},
        ),
    ]
