# Generated by Django 3.2.8 on 2021-10-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_todolistitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
